<?php
namespace SendyPHP\Exception;
/**
 * cURL exception
 *
 * Exception thrown if an error is generated by cURL module
 *
 * @package SendyPHP
 */
class CurlException extends RuntimeException
{
    /**
     * cURL exception
     *
     * @param string $message
     * @param resource|null $resource
     * @param int $code
     * @param \Exception $previous
     */
    public function __construct($message, $resource = NULL, $code = 0, \Exception $previous = null)
    {
        parent::__constuct($this->_buildMessage($message),$code,$previous);
    }
    /**
     * Builds Exception message text
     *
     * @param string $message
     * @param resource|null $resource
     * @return string
     */
    protected function _buildMessage($message, $resource = NULL)
    {
        $message = 'cURL '.$message;
        if(!is_null($resource))
        {
            $message.= ' cURL error: ['.curl_errno($resource).'] '.curl_error($resource);
        }
        return $message;
    }
}